- name: elasticsearch-restart
  service: >
    name={{ service_elasticsearch }}
    state=restarted

- name: elasticsearch-start
  service: >
    name={{ service_elasticsearch }}
    state=started

- name: elasticsearch-stop
  service: >
    name={{ service_elasticsearch }}
    state=stopped
